# Generated by Django 5.1.4 on 2025-01-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_location_listing_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(blank=True, choices=[("Inner St.John's", "Inner St.John's"), ("Outer St.John's", "Outer St.John's")], max_length=20, null=True),
        ),
    ]
