# Generated by Django 5.1.4 on 2025-01-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
    ]
