# Generated by Django 5.1.4 on 2025-02-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_rename_comment_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='pool',
            new_name='utilities',
        ),
    ]
