# Generated by Django 5.1.4 on 2025-02-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_rename_pool_listing_utilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='elevator',
            new_name='petfriendly',
        ),
    ]
