# Generated by Django 5.1.4 on 2025-02-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_rename_elevator_listing_petfriendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
