# Generated by Django 5.1.4 on 2025-02-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(default='Not Provided', max_length=150, null=True),
        ),
    ]
